# Generated by Django 5.2.6 on 2025-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_student_name_alter_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='lecturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=10),
        ),
    ]
